php-app/controllers/LekarzController.php
<?php

namespace app\controllers;

use app\models\LekarzPlacowkaMm;
use app\models\Placowka;
use Yii;
use app\models\Lekarz;
use app\models\LekarzSearch;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LekarzController implements the CRUD actions for Lekarz model.
 */
class LekarzController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lekarz models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LekarzSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Lekarz model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'availablePlacowkas' => Placowka::find()
                ->where(['not in', 'id', (new Query())->select('placowka_id')
                    ->from(LekarzPlacowkaMm::tableName())->where(['lekarz_id' => $id])])
                ->all(),
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Lekarz model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Lekarz();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Dodanie lekarza powiodło się.');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Lekarz model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            Yii::$app->getSession()->setFlash('success', 'Edycja lekarza powiodła się.');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Lekarz model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try{
            $this->findModel($id)->delete();
            Yii::$app->getSession()->setFlash('success', 'Usunięcie lekarza powiodło się.');
        }catch (\Exception $e){
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie lekarza nie powiodło się. Usuń wszystkie obraz, które lekarz zlecał lub wykonywał, aby usunąć tego lekarza.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Placowka belonged to Lekarz .
     * If deletion is successful, the browser will be redirected to the Lekarz 'view' page.
     * @param integer $idPlacowka
     * @param integer $idLekarz
     * @return mixed
     */
    public function actionDeletePlacowka($idPlacowka, $idLekarz)
    {
        /** @var LekarzPlacowkaMm $model */
        $model = LekarzPlacowkaMm::findOne(['placowka_id' => $idPlacowka, 'lekarz_id' => $idLekarz]);
        if (!$model) {
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie placowki, do ktorej należał lekarz nie powiodło się.');
        }
        $model->delete();
        Yii::$app->getSession()->setFlash('success', 'Usunięcie placowki, do ktorej należał lekarz powiodło się.');
        return $this->redirect(['view', 'id' => $idLekarz]);
    }

    /**
     * Add an existing Placowka to Lekarz.
     * If adding is successful, the browser will be redirected to the Lekarz 'view' page.
     * @return mixed
     */
    public function actionCreatePlacowka()
    {
        $model = new LekarzPlacowkaMm();

        $model->placowka_id = Yii::$app->request->post()['placowka_id'];
        $model->lekarz_id = Yii::$app->request->post()['lekarz_id'];

        if (!$model->save()) {
            Yii::$app->getSession()->setFlash('danger', 'Dodanie placowki, do ktorej należy lekarz nie powiodło się.');
        }

        Yii::$app->getSession()->setFlash('success', 'Dodanie placowki, do ktorej należy lekarz powiodło się.');
        return $this->redirect(['view', 'id' => $model->placowka_id]);
    }

    /**
     * Finds the Lekarz model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lekarz the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Lekarz::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php-app/controllers/ObrazController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Obraz;
use app\models\ObrazSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ObrazController implements the CRUD actions for Obraz model.
 */
class ObrazController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Obraz models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ObrazSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Obraz model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Obraz model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Obraz();
        try {
            if (!$model->load(Yii::$app->request->post())) {
                throw new \Exception;
            }
            if (!$model->file = UploadedFile::getInstance($model, 'file')) {
                $model->addError('file', 'Wystąpił błąd z wgrywanym plikiem');
                throw new \Exception;
            }

            $fileName = $model->file->baseName . '.' . $model->file->extension;

            if (is_file('uploads/' . $fileName)) {
                $model->addError('file', 'Plik o tej nazwie już istnieje');
                throw new \Exception;
            }
            if (!$model->file->saveAs('uploads/' . $fileName)) {
                $model->addError('file', 'Nie można zapisać pliku');
                throw new \Exception;
            }

            // saving the path in the db column
            $model->nazwa_pliku = $fileName;
            if (!$model->save()) {
                if (!unlink('uploads/' . $model->nazwa_pliku)) {
                    throw new \Exception;
                }
                Yii::$app->getSession()->setFlash('danger', 'Dodanie obrazu nie powiodło się.');
                throw new \Exception;
            }

            Yii::$app->getSession()->setFlash('success', 'Dodanie obrazu powiodło się');
            return $this->redirect(['view', 'id' => $model->id]);
        } catch (\Exception $e) {
            foreach ($model->getErrors('nazwa_pliku') as $error) {
                $model->addError('file', $error);
            }
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Obraz model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        try {
            if (!$model->load(Yii::$app->request->post())) {
                throw new \Exception;
            }

            if ($model->file = UploadedFile::getInstance($model, 'file')) {
                $fileName = $model->file->baseName . '.' . $model->file->extension;
                if (is_file('uploads/' . $fileName)) {
                    $model->addError('file', 'Plik o tej nazwie już istnieje');
                    throw new \Exception;
                }
                if (!$model->file->saveAs('uploads/' . $fileName)) {
                    $model->addError('file', 'Nie można zapisać pliku');
                    throw new \Exception;
                }
                if($model->nazwa_pliku){
                    unlink('uploads/' . $model->nazwa_pliku);
                }
                $model->nazwa_pliku = $fileName;
            }
            if (!$model->save()) {
                throw new \Exception;
            }
            Yii::$app->getSession()->setFlash('success', 'Edycja obrazu powiodła się');
            return $this->redirect(['view', 'id' => $model->id]);
        } catch (\Exception $e) {
            foreach ($model->getErrors('nazwa_pliku') as $error) {
                $model->addError('file', $error);
            }
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->getSession()->setFlash('danger', 'Edycja obrazu nie powiodła się.');
            }
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Obraz model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        try{
            if (unlink('uploads/' . $model->nazwa_pliku)) {
                $model->delete();
            }
            Yii::$app->getSession()->setFlash('success', 'Usunięcie obrazu powiodło się.');
        }catch (\Exception $e){
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie obrazu nie powiodło się.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Obraz model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Obraz the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Obraz::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php-app/controllers/PlacowkaController.php
<?php

namespace app\controllers;

use app\models\Lekarz;
use app\models\LekarzPlacowkaMm;
use app\models\Pacjent;
use Yii;
use app\models\Placowka;
use app\models\PlacowkaSearch;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PlacowkaController implements the CRUD actions for Placowka model.
 */
class PlacowkaController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'create-lekarz' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Placowka models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PlacowkaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Placowka model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'availableLekarzs' => Lekarz::find()
                ->where(['not in', 'id', (new Query())->select('lekarz_id')
                    ->from(LekarzPlacowkaMm::tableName())->where(['placowka_id' => $id])])
                ->all(),
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Placowka model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Placowka();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Dodanie placówki powiodło się');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Placowka model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Edycja placówki powiodła się');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Placowka model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
            Yii::$app->getSession()->setFlash('success', 'Usuwanie powiodło się.');
        } catch (\Exception $e) {
            Yii::$app->getSession()->setFlash('danger', 'Usuwanie nie powiodło się. Usuń wszystkich lekarzy zatrudnionych, aby usunąć placówkę.');
        }
        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Lakarz form Placowka.
     * If deletion is successful, the browser will be redirected to the Placowka 'view' page.
     * @param integer $idPlacowka
     * @param integer $idLekarz
     * @return mixed
     */
    public function actionDeleteLekarz($idPlacowka, $idLekarz)
    {
        /** @var LekarzPlacowkaMm $model */
        $model = LekarzPlacowkaMm::findOne(['placowka_id' => $idPlacowka, 'lekarz_id' => $idLekarz]);
        if (!$model) {
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie lekarza z placówki nie powiodło się.');
        }
        $model->delete();
        Yii::$app->getSession()->setFlash('success', 'Usunięcie lekarza z placówki powiodło się.');
        return $this->redirect(['view', 'id' => $idPlacowka]);
    }

    /**
     * Add an existing Lakarz to Placowka.
     * If adding is successful, the browser will be redirected to the Placowka 'view' page.
     * @return mixed
     */
    public function actionCreateLekarz()
    {
        $model = new LekarzPlacowkaMm();

        $model->placowka_id = Yii::$app->request->post()['placowka_id'];
        $model->lekarz_id = Yii::$app->request->post()['lekarz_id'];

        if (!$model->save()) {
            Yii::$app->getSession()->setFlash('danger', 'Dodanie lekarza do placówki nie powiodło się.');
        }

        Yii::$app->getSession()->setFlash('success', 'Dodanie lekarza do placówki powiodło się.');
        return $this->redirect(['view', 'id' => $model->placowka_id]);
    }

    /**
     * Finds the Placowka model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Placowka the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Placowka::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php-app/views/lekarz/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Lekarz */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="lekarz-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'imie')->textInput(['maxlength' => 45]) ?>

    <?= $form->field($model, 'nazwisko')->textInput(['maxlength' => 45]) ?>

    <?= $form->field($model, 'specjalizacja')->textInput(['maxlength' => 45]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Zatwierdź' : 'Zatwierdź', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

php-app/views/lekarz/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LekarzSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="lekarz-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'imie') ?>

    <?= $form->field($model, 'nazwisko') ?>

    <?= $form->field($model, 'specjalizacja') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

php-app/views/lekarz/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Lekarz */

$this->title = 'Dodaj Lekarza';
$this->params['breadcrumbs'][] = ['label' => 'Lekarze', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lekarz-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

php-app/views/lekarz/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\LekarzSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lekarze';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lekarz-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Dodaj Lekarza', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'imie',
            'nazwisko',
            'specjalizacja',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

php-app/views/lekarz/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Lekarz */

$this->title = 'Edytuj Lekarza: ' . ' ' . $model->nazwisko . ' ' . $model->imie;
$this->params['breadcrumbs'][] = ['label' => 'Lekarzs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Edytuj';
?>
<div class="lekarz-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

php-app/views/lekarz/view.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Lekarz */
/* @var $availablePlacowkas Placowka[] */

$this->title = $model->nazwisko . ' ' . $model->imie;
$this->params['breadcrumbs'][] = ['label' => 'Lekarze', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lekarz-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Edytuj', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Usuń', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'imie',
            'nazwisko',
            'specjalizacja',
        ],
    ]) ?>

    <h3>Zatrudniony w placówce</h3>
    <table class="table table-striped table-bordered detail-view">
        <?php
        foreach ($model->placowkas as $placowka) {
            echo '<tr><td>' . Html::a($placowka->nazwa, ['placowka/view', 'id' => $placowka->id], ['class' => 'lbtn'])
                . Html::a('Usuń placówkę', ['delete-placowka', 'idLekarz' => $model->id, 'idPlacowka' => $placowka->id],
                    ['class' => 'btn btn-danger btn-sm', 'style' => 'float:right'])
                .  '</td></tr>';
        }
        ?>
    </table>


    <?= Html::a('wszystkie zlecenia', ['obraz/index', 'ObrazSearch[lekarz_zlecajacy]'=>$model->id], ['class' => 'btn btn-info']) ?>
    <?= Html::a('wszystkie wykonania', ['obraz/index', 'ObrazSearch[lekarz_wykonujacy]'=>$model->id], ['class' => 'btn btn-info']) ?>

    <h3>Dodaj placówkę</h3>

    <?= Html::beginForm(['create-placowka']) ?>
    <?= Html::hiddenInput('placowka_id', $model->id) ?>
    <?= Html::dropDownList('lekarz_id', null,
        ArrayHelper::map($availablePlacowkas, 'id', 'nazwa'),
        ['prompt' => '','required' => '' , 'class' => 'btn btn-default dropdown-toggle']) ?>
    <?= Html::submitButton('Dodaj placowkę',
        ['class' => 'btn btn-success']) ?>
    <?= Html::endForm() ?>
</div>