php-app/models/Obraz.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "obraz".
 *
 * @property integer $id
 * @property string $nazwa
 * @property string $nazwa_pliku
 * @property string $data_utworzenia
 * @property integer $lekarz_zlecajacy
 * @property integer $lekarz_wykonujacy
 * @property integer $pacjent_id
 *
 * @property Lekarz $lekarzZlecajacy
 * @property Lekarz $lekarzWykonujacy
 * @property Pacjent $pacjent
 */
class Obraz extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'obraz';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nazwa', 'nazwa_pliku', 'data_utworzenia', 'lekarz_zlecajacy', 'lekarz_wykonujacy', 'pacjent_id'], 'required'],
            [['data_utworzenia'], 'safe'],
            [['data_utworzenia'], 'date', 'format' => 'yyyy-MM-dd'],
            [['lekarz_zlecajacy', 'lekarz_wykonujacy', 'pacjent_id'], 'integer'],
            [['nazwa'], 'string', 'max' => 45],
            [['nazwa_pliku'], 'string', 'max' => 100],
            [['nazwa_pliku'], 'unique'],
            [['file'], 'file'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nazwa' => 'Nazwa',
            'nazwa_pliku' => 'Obraz',
            'data_utworzenia' => 'Data Utworzenia',
            'lekarz_zlecajacy' => 'Lekarz Zlecający',
            'lekarz_wykonujacy' => 'Lekarz Wykonujący',
            'pacjent_id' => 'Pacjent',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLekarzZlecajacy()
    {
        return $this->hasOne(Lekarz::className(), ['id' => 'lekarz_zlecajacy']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLekarzWykonujacy()
    {
        return $this->hasOne(Lekarz::className(), ['id' => 'lekarz_wykonujacy']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPacjent()
    {
        return $this->hasOne(Pacjent::className(), ['id' => 'pacjent_id']);
    }
}

php-app/controllers/LekarzController.php
<?php

namespace app\controllers;

use app\models\LekarzPlacowkaMm;
use app\models\Placowka;
use Yii;
use app\models\Lekarz;
use app\models\LekarzSearch;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LekarzController implements the CRUD actions for Lekarz model.
 */
class LekarzController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lekarz models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LekarzSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Lekarz model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'availablePlacowkas' => Placowka::find()
                ->where(['not in', 'id', (new Query())->select('placowka_id')
                    ->from(LekarzPlacowkaMm::tableName())->where(['lekarz_id' => $id])])
                ->all(),
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Lekarz model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Lekarz();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Dodanie lekarza powiodło się.');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Lekarz model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            Yii::$app->getSession()->setFlash('success', 'Edycja lekarza powiodła się.');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Lekarz model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try{
            $this->findModel($id)->delete();
            Yii::$app->getSession()->setFlash('success', 'Usunięcie lekarza powiodło się.');
        }catch (\Exception $e){
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie lekarza nie powiodło się. Usuń wszystkie obraz, które lekarz zlecał lub wykonywał, aby usunąć tego lekarza.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Placowka belonged to Lekarz .
     * If deletion is successful, the browser will be redirected to the Lekarz 'view' page.
     * @param integer $idPlacowka
     * @param integer $idLekarz
     * @return mixed
     */
    public function actionDeletePlacowka($idPlacowka, $idLekarz)
    {
        /** @var LekarzPlacowkaMm $model */
        $model = LekarzPlacowkaMm::findOne(['placowka_id' => $idPlacowka, 'lekarz_id' => $idLekarz]);
        if (!$model) {
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie placowki, do ktorej należał lekarz nie powiodło się.');
        }
        $model->delete();
        Yii::$app->getSession()->setFlash('success', 'Usunięcie placowki, do ktorej należał lekarz powiodło się.');
        return $this->redirect(['view', 'id' => $idLekarz]);
    }

    /**
     * Add an existing Placowka to Lekarz.
     * If adding is successful, the browser will be redirected to the Lekarz 'view' page.
     * @return mixed
     */
    public function actionCreatePlacowka()
    {
        $model = new LekarzPlacowkaMm();

        $model->placowka_id = Yii::$app->request->post()['placowka_id'];
        $model->lekarz_id = Yii::$app->request->post()['lekarz_id'];

        if (!$model->save()) {
            Yii::$app->getSession()->setFlash('danger', 'Dodanie placowki, do ktorej należy lekarz nie powiodło się.');
        }

        Yii::$app->getSession()->setFlash('success', 'Dodanie placowki, do ktorej należy lekarz powiodło się.');
        return $this->redirect(['view', 'id' => $model->placowka_id]);
    }

    /**
     * Finds the Lekarz model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lekarz the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Lekarz::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php-app/controllers/ObrazController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Obraz;
use app\models\ObrazSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ObrazController implements the CRUD actions for Obraz model.
 */
class ObrazController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Obraz models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ObrazSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Obraz model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Obraz model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Obraz();
        try {
            if (!$model->load(Yii::$app->request->post())) {
                throw new \Exception;
            }
            if (!$model->file = UploadedFile::getInstance($model, 'file')) {
                $model->addError('file', 'Wystąpił błąd z wgrywanym plikiem');
                throw new \Exception;
            }

            $fileName = $model->file->baseName . '.' . $model->file->extension;

            if (is_file('uploads/' . $fileName)) {
                $model->addError('file', 'Plik o tej nazwie już istnieje');
                throw new \Exception;
            }
            if (!$model->file->saveAs('uploads/' . $fileName)) {
                $model->addError('file', 'Nie można zapisać pliku');
                throw new \Exception;
            }

            // saving the path in the db column
            $model->nazwa_pliku = $fileName;
            if (!$model->save()) {
                if (!unlink('uploads/' . $model->nazwa_pliku)) {
                    throw new \Exception;
                }
                Yii::$app->getSession()->setFlash('danger', 'Dodanie obrazu nie powiodło się.');
                throw new \Exception;
            }

            Yii::$app->getSession()->setFlash('success', 'Dodanie obrazu powiodło się');
            return $this->redirect(['view', 'id' => $model->id]);
        } catch (\Exception $e) {
            foreach ($model->getErrors('nazwa_pliku') as $error) {
                $model->addError('file', $error);
            }
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Obraz model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        try {
            if (!$model->load(Yii::$app->request->post())) {
                throw new \Exception;
            }

            if ($model->file = UploadedFile::getInstance($model, 'file')) {
                $fileName = $model->file->baseName . '.' . $model->file->extension;
                if (is_file('uploads/' . $fileName)) {
                    $model->addError('file', 'Plik o tej nazwie już istnieje');
                    throw new \Exception;
                }
                if (!$model->file->saveAs('uploads/' . $fileName)) {
                    $model->addError('file', 'Nie można zapisać pliku');
                    throw new \Exception;
                }
                if($model->nazwa_pliku){
                    unlink('uploads/' . $model->nazwa_pliku);
                }
                $model->nazwa_pliku = $fileName;
            }
            if (!$model->save()) {
                throw new \Exception;
            }
            Yii::$app->getSession()->setFlash('success', 'Edycja obrazu powiodła się');
            return $this->redirect(['view', 'id' => $model->id]);
        } catch (\Exception $e) {
            foreach ($model->getErrors('nazwa_pliku') as $error) {
                $model->addError('file', $error);
            }
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->getSession()->setFlash('danger', 'Edycja obrazu nie powiodła się.');
            }
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Obraz model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        try{
            if (unlink('uploads/' . $model->nazwa_pliku)) {
                $model->delete();
            }
            Yii::$app->getSession()->setFlash('success', 'Usunięcie obrazu powiodło się.');
        }catch (\Exception $e){
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie obrazu nie powiodło się.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Obraz model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Obraz the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Obraz::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php-app/controllers/PacjentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pacjent;
use app\models\PacjentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PacjentController implements the CRUD actions for Pacjent model.
 */
class PacjentController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pacjent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PacjentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pacjent model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pacjent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pacjent();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Dodanie pacjenta powiodło się.');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pacjent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pacjent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try{
            $this->findModel($id)->delete();
            Yii::$app->getSession()->setFlash('success', 'Usunięcie pacjenta powiodło się.');
        }catch (\Exception $e){
            Yii::$app->getSession()->setFlash('danger', 'Usunięcie pacjenta nie powiodło się.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pacjent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pacjent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pacjent::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php-app/views/obraz/_form.php
<?php

use app\models\Lekarz;
use app\models\Pacjent;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Obraz */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="obraz-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'nazwa')->textInput(['maxlength' => 45]) ?>

    <?php if ($model->nazwa_pliku) {
        echo Html::img('uploads/' . $model->nazwa_pliku);
    } ?>

    <?= $form->field($model, 'file')->fileInput() ?>

    <?= $form->field($model, 'data_utworzenia')->textInput() ?>

    <?= $form->field($model, 'lekarz_zlecajacy')
        ->dropDownList(
            ArrayHelper::map(Lekarz::find()->all(), 'id', 'nazwa'),
            ['prompt' => '']
        ); ?>

    <?= $form->field($model, 'lekarz_wykonujacy')
        ->dropDownList(
            ArrayHelper::map(Lekarz::find()->all(), 'id', 'nazwa'),
            ['prompt' => '']
        ); ?>

    <?= $form->field($model, 'pacjent_id')
        ->dropDownList(
            ArrayHelper::map(Pacjent::find()->all(), 'id', 'nazwa'),
            ['prompt' => '']
        ); ?>

    <div class="form-group">
        <?= Html::submitButton('Zatwierdź', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

php-app/views/obraz/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ObrazSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="obraz-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nazwa') ?>

    <?= $form->field($model, 'nazwa_pliku') ?>

    <?= $form->field($model, 'data_utworzenia') ?>

    <?= $form->field($model, 'lekarz_zlecajacy') ?>

    <?php // echo $form->field($model, 'lekarz_wykonujacy') ?>

    <?php // echo $form->field($model, 'pacjent_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

php-app/views/obraz/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Obraz */

$this->title = 'Dodaj Obraz';
$this->params['breadcrumbs'][] = ['label' => 'Obrazy', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="obraz-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

php-app/views/obraz/index.php
<?php

use app\models\Lekarz;
use app\models\Obraz;
use app\models\Pacjent;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ObrazSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Obrazy';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="obraz-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Dodaj Obraz', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'id',
                'headerOptions' => ['width' => '70'],
            ],
            'nazwa',
            [
                'attribute' => 'nazwa_pliku',
                'format' => 'html',
                'value' => function (Obraz $model) {
                    return Html::img('uploads/' . $model->nazwa_pliku);
                },
            ],
            [
                'attribute' => 'data_utworzenia',
                'filter' =>
                    Html::tag('span', 'od:') . Html::activeInput('date', $searchModel, 'data_od', ['class' => 'form-control']) . Html::tag('br')
                    . Html::tag('span', 'do:') . Html::activeInput('date', $searchModel, 'data_do', ['class' => 'form-control']),
            ],
            [
                'attribute' => 'lekarz_zlecajacy',
                'format' => 'html',
                'value' => function (Obraz $model) {
                    return Html::a($model->lekarzZlecajacy->getNazwa(), ['lekarz/view', 'id' => $model->lekarzZlecajacy->id]);
                },
                'filter' => ArrayHelper::map(Lekarz::find()->all(), 'id', 'nazwa'),
            ],
            [
                'attribute' => 'lekarz_wykonujacy',
                'format' => 'html',
                'value' => function (Obraz $model) {
                    return Html::a($model->lekarzWykonujacy->getNazwa(), ['lekarz/view', 'id' => $model->lekarzWykonujacy->id]);
                },
                'filter' => ArrayHelper::map(Lekarz::find()->all(), 'id', 'nazwa'),
            ],
            [
                'attribute' => 'pacjent_id',
                'format' => 'html',
                'value' => function (Obraz $model) {
                    return Html::a($model->pacjent->getNazwa(), ['pacjent/view', 'id' => $model->pacjent->id]);
                },
                'filter' => ArrayHelper::map(Pacjent::find()->all(), 'id', 'nazwa'),
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['class' => 'text-nowrap'],
            ],
        ],
    ]); ?>

</div>

php-app/views/obraz/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Obraz */

$this->title = 'Edytuj Obraz: ' . ' ' . $model->nazwa;
$this->params['breadcrumbs'][] = ['label' => 'Obrazy', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nazwa, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Edytuj';
?>
<div class="obraz-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

php-app/views/obraz/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Obraz */

$this->title = $model->nazwa;
$this->params['breadcrumbs'][] = ['label' => 'Obrazy', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="obraz-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Edytuj', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Usuń', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Czy na pewno chcesz usunąć ten obraz?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nazwa',
            [
                'attribute' => 'nazwa_pliku',
                'format' => 'html',
                'value' => Html::img('uploads/' . $model->nazwa_pliku),
            ],
            'data_utworzenia',
            [
                'attribute' => 'lekarz_zlecajacy',
                'format' => 'html',
                'value' => Html::a($model->lekarzZlecajacy->getNazwa(), ['lekarz/view', 'id' => $model->lekarzZlecajacy->id]),
            ],
            [
                'attribute' => 'lekarz_wykonujacy',
                'format' => 'html',
                'value' => Html::a($model->lekarzWykonujacy->getNazwa(), ['lekarz/view', 'id' => $model->lekarzWykonujacy->id]),
            ],
            [
                'attribute' => 'pacjent_id',
                'format' => 'html',
                'value' => Html::a($model->pacjent->getNazwa(), ['pacjent/view', 'id' => $model->pacjent->id]),
            ],
        ],
    ]) ?>

</div>